.Dd January 19, 2010
.Dt IRCLOG2PF 1
.Os FreeBSD
.Sh NAME
.Nm irclog2pf
.Nd grabs hostnames from IRC logs and adds them to a PF table
.Sh
.Nm
.Op Fl t Ar table
.Op Fl v 
.Sh DESCRIPTION
.Nm irclog2pf
adds IP addresses and hostmasks found in IRC log files to a PF table by 
looking for the pattern "user@host". 
.Nm REQUIREMENTS
For 
.Nm irclog2pf
to be effective the table you're trying to add IP addresses to must exist. A
PF block rule should also be associated with the table. An example setup may
look something like:
.PP
table <drones>
.PP
block drop in log quick on $ext_if from <drones> to ($ext_if)
.Sh FILES
.Bl -tag -width "/etc/pf.conf"
.It /etc/pf.conf
Default location of the PF configuration file.
.Sh SEE ALSO
.Xr pfctl 8
.Sh AUTHORS
.An Svante Kvarnstrom Aq sjk@ankeborg.nu
